// ============================================================
// PRESENSI.JS - COMPACT PREMIUM EDITION (v5.5.0)
// ============================================================
const GITHUB_LOGO_URL="https://raw.githubusercontent.com/tpopbwi/presensi-pusda/main/assets/logo.png",API="https://script.google.com/macros/s/AKfycbw3rVOUuD6viUevnvcI-JcCg114syXT1IZRy6QegkTR1z05vqnKm7H4TGAgbxJ1_O8iag/exec";
let appConfig={jHadir:"08:00",jTelat:"08:11",jPulang:"10:00"};

// PWA MANIFEST
try{const m={name:"E-PUSDA Presensi",short_name:"E-Presensi",start_url:"./presensi.html",scope:"./",display:"standalone",background_color:"#0d1b3e",theme_color:"#1e40af",icons:[{src:GITHUB_LOGO_URL,sizes:"192x192",type:"image/png"},{src:GITHUB_LOGO_URL,sizes:"512x512",type:"image/png",purpose:"any maskable"}]};const b=new Blob([JSON.stringify(m)],{type:'application/manifest+json'});const u=URL.createObjectURL(b);const e=document.getElementById('pwaManifest');if(e)e.setAttribute('href',u);else{const l=document.createElement('link');l.rel='manifest';l.href=u;document.head.appendChild(l);}}catch(e){}

// POLYFILL & GLOBALS
if(!CanvasRenderingContext2D.prototype.roundRect){CanvasRenderingContext2D.prototype.roundRect=function(x,y,w,h,r){r=Math.min(r,w/2,h/2);this.beginPath();this.moveTo(x+r,y);this.arcTo(x+w,y,x+w,y+h,r);this.arcTo(x+w,y+h,x,y+h,r);this.arcTo(x,y+h,x,y,r);this.arcTo(x,y,x+w,y,r);this.closePath();return this;};}
let isFaceApiLoaded=false,isFaceApiLoading=false,isInitialMapBound=false,_lastFrameTime=0,isFormLoading=false,_lastToastKey='',_lastToastTime=0;
let dbE=[],dbF=[],dbP=[],uIdx=0,map=null,marker=null,uPos={lat:0,lng:0},cType='',sB64=null,kB64=null,selectedStatus='',calculatedScore=0;
let isLandmarkReady=false,pendingCamType=null,currentStream=null,lastGoodDetection=null,faceDetected=false,detectionStableCount=0;
const STABLE_THRESHOLD=3,detectIntervalId=null,suratB64=null;
let laserY=0,laserDirection=1,_canvasW=0,_canvasH=0,_rafRunning=false,_activeResizeHandler=null;
const sndShutter=new Audio('https://assets.mixkit.co/active_storage/sfx/738/738-preview.mp3');
const sndSuccess=new Audio('https://assets.mixkit.co/active_storage/sfx/1435/1435-preview.mp3');
const sndError=new Audio('https://assets.mixkit.co/active_storage/sfx/2571/2571-preview.mp3');
const logoCache=new Image();logoCache.crossOrigin="anonymous";logoCache.src=GITHUB_LOGO_URL;
const placeholderImg="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 60 85'%3E%3Crect width='60' height='85' fill='%232e446e'/%3E%3Cpath d='M30 40c5.5 0 10-4.5 10-10s-4.5-10-10-10-10 4.5-10 10 4.5 10 10 10zm0 5c-8 0-20 4-20 12v5h40v-5c0-8-12-12-20-12z' fill='%23fff' opacity='.2'/%3E%3C/svg%3E";

// DEVICE PROFILE
const DeviceProfile=(()=>{const c=navigator.hardwareConcurrency||2,r=navigator.deviceMemory||2,n=navigator.connection?['slow-2g','2g','3g'].includes(navigator.connection.effectiveType):false;let t='low';if(r>=4&&c>=6&&!n)t='high';else if(r>=3&&c>=4)t='mid';const cfg={high:{enableFaceAPI:true,enableLandmarks:true,enableShadowBlur:true,canvasFPS:60,detectInterval:200,selfieResolution:[800,600],kerjaResolution:[800,600],jpegQuality:0.5,videoConstraints:{width:1280,height:960}},mid:{enableFaceAPI:true,enableLandmarks:true,enableShadowBlur:false,canvasFPS:30,detectInterval:350,selfieResolution:[800,600],kerjaResolution:[800,600],jpegQuality:0.5,videoConstraints:{width:960,height:720}},low:{enableFaceAPI:false,enableLandmarks:false,enableShadowBlur:false,canvasFPS:30,detectInterval:0,selfieResolution:[800,600],kerjaResolution:[800,600],jpegQuality:0.5,videoConstraints:{width:640,height:480}}};return{tier:t,config:cfg[t]};})();

// STATUS CONFIG
const STATUS_CONFIG={'HADIR':{placeholder:'Tuliskan ringkasan tugas hari ini...',title:'✅ HADIR',message:'<b>Aturan Waktu:</b><br>• ≤ 08:10 = Poin 50<br>• 08:11 = Poin 40<br>• > 08:11 = Poin 25',icon:'check-circle',color:'var(--success)',borderColor:'var(--success)',actions:[]},'PULANG':{placeholder:'Tuliskan ringkasan hasil kerja hari ini...',title:'🌙 PULANG',message:'Absensi pulang tercatat. Selamat beristirahat.',icon:'moon',color:'var(--pu-blue)',borderColor:'var(--pu-blue)',actions:[]},'IZIN':{placeholder:'Jelaskan alasan izin...',title:'📝 IZIN',message:'Silahkan hubungi Koordinator.',icon:'file-text',color:'#d8b4fe',borderColor:'#a855f7',actions:[{label:'Lampirkan Surat',icon:'paperclip',action:'uploadSurat'}]},'SAKIT':{placeholder:'Jelaskan kondisi sakit...',title:'🏥 SAKIT',message:'Lampirkan foto surat dokter.',icon:'heart-pulse',color:'#fde047',borderColor:'var(--warning)',actions:[{label:'Lampirkan Surat Dokter',icon:'paperclip',action:'uploadSurat'}]},'DINAS':{placeholder:'Jelaskan lokasi dinas...',title:'💼 DINAS',message:'Lampirkan foto surat tugas.',icon:'briefcase',color:'#fdba74',borderColor:'var(--accent)',actions:[{label:'Lampirkan Surat Tugas',icon:'paperclip',action:'uploadSurat'}]},'QUICK RESPONSE':{placeholder:'Tuliskan ringkasan tugas darurat...',title:'⚡ QUICK RESPONSE',message:'Tuliskan ringkasan tugas hari ini.',icon:'zap',color:'#f9a8d4',borderColor:'#ec4899',actions:[]}};

// ============================================================
// MISSION CONTROL SYSTEM (Premium UX)
// ============================================================
const MissionControl={el:null,steps:[{id:'mc-val',icon:'shield-check',title:'Memvalidasi Data',desc:'Keamanan & Integritas'},{id:'mc-loc',icon:'map-pin-check',title:'Mengamankan Lokasi',desc:'Enkripsi Koordinat GPS'},{id:'mc-upl',icon:'cloud-upload',title:'Mengunggah Bukti',desc:'Mengirim ke Server Aman'},{id:'mc-sync',icon:'database',title:'Menyinkronkan Data',desc:'Menulis ke Database'}],cur:-1,
init(){if(this.el)return;this.el=document.createElement('div');this.el.id='missionControl';this.el.innerHTML=`<div class="mc-container" style="position:relative"><div class="mc-title">SISTEM PRESENSI AKTIF</div>${this.steps.map(s=>`<div class="mc-step" id="${s.id}"><div class="mc-icon"><i data-lucide="${s.icon}" size="18"></i></div><div class="mc-text"><h4>${s.title}</h4><p>${s.desc}</p></div></div>`).join('')}<div class="mc-success-burst" id="mcBurst"><svg viewBox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div></div>`;document.body.appendChild(this.el);lucide.createIcons();},
async start(){this.init();this.cur=-1;this.steps.forEach(s=>{const e=document.getElementById(s.id);e.classList.remove('active','done');e.querySelector('.mc-icon').style.color='';e.querySelector('.mc-text h4').style.color='';});document.getElementById('mcBurst').classList.remove('show');this.el.style.display='flex';requestAnimationFrame(()=>this.el.classList.add('active'));},
async nextStep(){this.cur++;if(this.cur>=this.steps.length)return;const s=this.steps[this.cur],e=document.getElementById(s.id);if(this.cur>0){const p=document.getElementById(this.steps[this.cur-1].id);p.classList.remove('active');p.classList.add('done');p.querySelector('.mc-icon').innerHTML='<i data-lucide="check" size="18"></i>';lucide.createIcons();haptic();}e.classList.add('active');await new Promise(r=>setTimeout(r,400));},
async showSuccess(){const l=document.getElementById(this.steps[this.cur].id);l.classList.remove('active');l.classList.add('done');l.querySelector('.mc-icon').innerHTML='<i data-lucide="check" size="18"></i>';lucide.createIcons();await new Promise(r=>setTimeout(r,300));document.getElementById('mcBurst').classList.add('show');sndSuccess.play().catch(()=>{});haptic();await new Promise(r=>setTimeout(r,1500));this.el.classList.add('fade-out');await new Promise(r=>setTimeout(r,400));this.el.style.display='none';this.el.classList.remove('active','fade-out');},
showError(msg){if(this.cur>=0){const e=document.getElementById(this.steps[this.cur].id);e.querySelector('.mc-icon').style.color='#ef4444';e.querySelector('.mc-text h4').style.color='#ef4444';e.querySelector('.mc-text p').innerText=msg;e.classList.remove('active');}},
hide(){if(!this.el)return;this.el.classList.add('fade-out');setTimeout(()=>{this.el.style.display='none';this.el.classList.remove('active','fade-out');},300);}};

// ============================================================
// CORE UTILITIES
// ============================================================
function haptic(){if(navigator.vibrate)navigator.vibrate(50);}
function logPerformance(a,m){try{const l=JSON.parse(localStorage.getItem('pusda_perf_log')||'[]');l.push({action:a,ms:Math.round(m),time:Date.now()});localStorage.setItem('pusda_perf_log',JSON.stringify(l.slice(-50)));}catch(e){}}
function saveLastPegawai(p){try{localStorage.setItem('pusda_last_pegawai',JSON.stringify({id:p.ID||p.id,nama:p.Nama||p.nama}));}catch(e){}}

async function ensureFaceApiLoaded(){if(isFaceApiLoaded)return true;if(isFaceApiLoading){while(isFaceApiLoading)await new Promise(r=>setTimeout(r,100));return isFaceApiLoaded;}isFaceApiLoading=true;showToast("Memuat AI","Menyiapkan deteksi wajah...","info");try{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@vladmandic/face-api/dist/face-api.js';document.head.appendChild(s);await Promise.race([new Promise((res,rej)=>{s.onload=res;s.onerror=rej;}),new Promise((_,rej)=>setTimeout(()=>rej(new Error('Timeout')),10000))]);await faceapi.nets.tinyFaceDetector.loadFromUri('https://cdn.jsdelivr.net/npm/@vladmandic/face-api/model/');isFaceApiLoaded=true;isFaceApiLoading=false;return true;}catch(e){console.error("Face API Error:",e);isFaceApiLoading=false;showToast("Mode AI Gagal","Menggunakan mode standar","warning");return false;}}

function fetchWithTimeout(u,o={},t=15000){const c=new AbortController();const id=setTimeout(()=>c.abort(new DOMException('Timeout','AbortError')),t);return fetch(u,{...o,signal:c.signal}).finally(()=>clearTimeout(id));}
async function fetchWithRetry(u,o={},r=2,d=1500){for(let i=0;i<=r;i++){try{const res=await fetchWithTimeout(u,o);if(res.ok)return res;throw new Error(`HTTP ${res.status}`);}catch(e){if(i===r)throw e;await new Promise(res=>setTimeout(res,d*(i+1)));}}}
async function safeFetchJSON(u,o={},t=15000){try{const r=await fetchWithTimeout(u,o,t);if(!r.ok)throw new Error('HTTP '+r.status);const txt=await r.text();if(!txt||!txt.trim())throw new Error('Response kosong');if(txt.trim().startsWith('<!DOCTYPE'))throw new Error('Server HTML Error');return JSON.parse(txt);}catch(e){if(e.name==='AbortError'||e.message?.includes('Timeout')){const err=new Error('Timeout koneksi');err.name='TimeoutError';throw err;}throw e;}}

function showToast(t,m,type="info"){const modal=document.getElementById('notificationModal');if(!modal)return;const c=document.getElementById('notifModalContent');c.className='notif-modal-content';c.classList.add(`notif-${type}`);document.getElementById('notifTitle').innerText=t;document.getElementById('notifMessage').innerText=m;document.getElementById('notifIcon').setAttribute('data-lucide',{success:'check-circle',error:'x-circle',warning:'alert-triangle',info:'info'}[type]||'info');document.getElementById('btnNotifOk').innerHTML='<i data-lucide="check" size="18"></i> Mengerti';lucide.createIcons();modal.style.display='flex';requestAnimationFrame(()=>modal.classList.add('show'));if(type==='success')sndSuccess.play().catch(()=>{});else if(type==='error'||type==='warning')sndError.play().catch(()=>{});const cl=()=>{modal.classList.remove('show');setTimeout(()=>modal.style.display='none',300);};const at=setTimeout(cl,4000);document.getElementById('btnNotifOk').onclick=()=>{clearTimeout(at);cl();};}
function showToastOnce(k,t,m,type,min=30000){const n=Date.now();if(_lastToastKey===k&&(n-_lastToastTime)<min)return;_lastToastKey=k;_lastToastTime=n;showToast(t,m,type);}
function setLoading(s,t){const o=document.getElementById('sendingOverlay');document.getElementById('overlayText').innerText=t;o.style.display=s?'flex':'none';o.style.pointerEvents=s?'all':'none';}

// ============================================================
// CANVAS & CAMERA RENDERING (COMPACT)
// ============================================================
function setupCanvas(){const c=document.getElementById('faceOverlay');if(!c)return;const v=document.getElementById('vStream');let w,h;if(v&&v.videoWidth>0&&v.videoHeight>0){w=v.videoWidth;h=v.videoHeight;}else{const r=c.getBoundingClientRect();w=Math.round(r.width);h=Math.round(r.height);}if(w<=0||h<=0)return;if(Math.abs(w-_canvasW)>3||Math.abs(h-_canvasH)>3){c.width=w;c.height=h;_canvasW=w;_canvasH=h;}}
function startRenderLoop(cb){if(_rafRunning)return;_rafRunning=true;const fps=1000/(DeviceProfile.tier==='low'?24:30);const loop=t=>{if(!_rafRunning)return;if(t-_lastFrameTime>=fps){cb(t);_lastFrameTime=t;}requestAnimationFrame(loop);};requestAnimationFrame(loop);}
function stopRenderLoop(){_rafRunning=false;}

function stopCurrentStream(){if(currentStream){currentStream.getTracks().forEach(t=>t.stop());currentStream=null;}const v=document.getElementById('vStream');if(v&&v.srcObject)v.srcObject=null;if(v)v.classList.remove('mirror');stopRenderLoop();if(detectIntervalId){clearInterval(detectIntervalId);detectIntervalId=null;}if(_activeResizeHandler){window.removeEventListener('resize',_activeResizeHandler);_activeResizeHandler=null;}const c=document.getElementById('faceOverlay');if(c)c.getContext('2d').clearRect(0,0,c.width,c.height);lastGoodDetection=null;faceDetected=false;detectionStableCount=0;laserY=0;laserDirection=1;_canvasW=0;_canvasH=0;}
function registerResizeHandler(){if(_activeResizeHandler)window.removeEventListener('resize',_activeResizeHandler);_activeResizeHandler=setupCanvas;window.addEventListener('resize',_activeResizeHandler);}

// Canvas Draw Helpers
function drawCornerBrackets(c,W,H,col,glow){const p=Math.min(W,H)*.08,l=Math.min(W,H)*.08;c.save();c.strokeStyle=col;c.lineWidth=3;c.lineCap='round';if(DeviceProfile.config.enableShadowBlur){c.shadowColor=glow;c.shadowBlur=5;}c.beginPath();c.moveTo(p,p+l);c.lineTo(p,p);c.lineTo(p+l,p);c.stroke();c.beginPath();c.moveTo(W-p-l,p);c.lineTo(W-p,p);c.lineTo(W-p,p+l);c.stroke();c.beginPath();c.moveTo(p,H-p-l);c.lineTo(p,H-p);c.lineTo(p+l,H-p);c.stroke();c.beginPath();c.moveTo(W-p-l,H-p);c.lineTo(W-p,H-p);c.lineTo(W-p,H-p-l);c.stroke();c.restore();}
function drawLaserLine(c,W,H,col){laserY+=laserDirection*3;if(laserY>=H*.85)laserDirection=-1;if(laserY<=H*.15)laserDirection=1;const g=c.createLinearGradient(0,laserY,W,laserY);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.2,col);g.addColorStop(.8,col);g.addColorStop(1,'rgba(0,0,0,0)');c.save();if(DeviceProfile.config.enableShadowBlur){c.shadowColor=col;c.shadowBlur=8;}c.strokeStyle=g;c.lineWidth=3;c.beginPath();c.moveTo(0,laserY);c.lineTo(W,laserY);c.stroke();c.shadowBlur=0;c.strokeStyle='rgba(255,255,255,.9)';c.lineWidth=1;c.beginPath();c.moveTo(0,laserY);c.lineTo(W,laserY);c.stroke();c.restore();}
function drawFaceGuide(c,W,H,col,glow){const cx=W/2,cy=H*.40,rx=Math.min(W,H)*.25,ry=Math.min(W,H)*.32,t=performance.now()/1000;c.save();c.setLineDash([15,10]);c.lineDashOffset=-t*40;c.strokeStyle=col;c.lineWidth=2.5;if(DeviceProfile.config.enableShadowBlur){c.shadowColor=glow;c.shadowBlur=6;}c.beginPath();c.ellipse(cx,cy,rx,ry,0,0,Math.PI*2);c.stroke();c.setLineDash([]);c.shadowBlur=0;c.restore();}
function drawRuleOfThirds(c,W,H){c.save();c.strokeStyle='rgba(34,211,238,0.25)';c.lineWidth=1;c.setLineDash([6,6]);c.beginPath();c.moveTo(W/3,0);c.lineTo(W/3,H);c.moveTo(2*W/3,0);c.lineTo(2*W/3,H);c.moveTo(0,H/3);c.lineTo(W,H/3);c.moveTo(0,2*H/3);c.lineTo(W,2*H/3);c.stroke();c.setLineDash([]);c.restore();}
function drawCrosshair(c,W,H,col){const cx=W/2,cy=H/2,o=25,g=4;c.save();c.strokeStyle=col;c.lineWidth=2;c.lineCap='round';if(DeviceProfile.config.enableShadowBlur){c.shadowColor=col;c.shadowBlur=8;}c.beginPath();c.moveTo(cx-o,cy);c.lineTo(cx-g,cy);c.moveTo(cx+g,cy);c.lineTo(cx+o,cy);c.moveTo(cx,cy-o);c.lineTo(cx,cy-g);c.moveTo(cx,cy+g);c.lineTo(cx,cy+o);c.stroke();c.restore();}
function drawWorkLabel(c,W,H){c.save();const l='WORK SITE',fs=Math.max(11,Math.round(W*0.022));c.font=`800 ${fs}px 'JetBrains Mono',monospace`;const tw=c.measureText(l).width,x=20,y=H*.12;const bw=tw+24,bh=fs+12;c.fillStyle='rgba(34,211,238,0.15)';c.strokeStyle='rgba(34,211,238,0.6)';c.lineWidth=1.5;c.beginPath();c.roundRect(x,y,bw,bh,8);c.fill();c.stroke();c.fillStyle='rgba(34,211,238,0.95)';c.textBaseline='middle';c.fillText(l,x+12,y+bh/2);c.restore();}

function drawFaceWireframe(c,det,W,H,col){const pos=det.landmarks.positions,box=det.detection.box;const vW=det.detection.imageWidth||document.getElementById('vStream').videoWidth,vH=det.detection.imageHeight||document.getElementById('vStream').videoHeight;if(!vW||!vH)return;const vR=vW/vH,cR=W/H;let dW,dH,oX,oY;if(vR>cR){dH=H;dW=H*vR;oX=(W-dW)/2;oY=0;}else{dW=W;dH=W/vR;oX=0;oY=(H-dH)/2;}const sX=dW/vW,sY=dH/vH,isM=cType==='selfie';const tx=vx=>{let x=vx*sX+oX;return isM?W-x:x;},ty=vy=>vy*sY+oY;let bx=tx(box.x),by=ty(box.y),bw=box.width*sX,bh=box.height*sY;if(isM)bx=bx-bw;c.save();c.strokeStyle=col.replace('0.9','0.4');c.lineWidth=1;c.setLineDash([5,5]);c.strokeRect(bx-10,by-10,bw+20,bh+20);c.setLineDash([]);c.strokeStyle=col;c.lineWidth=2;c.fillStyle=col;c.font=`bold ${Math.max(12,W*.018)}px 'JetBrains Mono'`;c.fillText(`FACE • ${(det.detection.score*100).toFixed(0)}%`,bx,by-15);c.strokeRect(bx,by,bw,bh);c.restore();}

// ============================================================
// OVERLAY TRIGGERS
// ============================================================
function startSelfieOverlay(){const c=document.getElementById('faceOverlay'),v=document.getElementById('vStream'),ctx=c.getContext('2d');lastGoodDetection=null;faceDetected=false;detectionStableCount=0;laserY=0;laserDirection=1;_canvasW=0;_canvasH=0;setupCanvas();registerResizeHandler();if(DeviceProfile.config.enableFaceAPI&&DeviceProfile.config.detectInterval>0){detectIntervalId=setInterval(async()=>{if(!currentStream||v.readyState!==4||v.videoWidth===0)return;try{const o=new faceapi.TinyFaceDetectorOptions({inputSize:DeviceProfile.tier==='high'?416:320,scoreThreshold:0.4});const d=await faceapi.detectSingleFace(v,o).withFaceLandmarks();if(d){lastGoodDetection=d;detectionStableCount++;if(detectionStableCount>=STABLE_THRESHOLD&&!faceDetected){faceDetected=true;updateStatusUI(true);}}else if(faceDetected){faceDetected=false;lastGoodDetection=null;updateStatusUI(false);detectionStableCount=0;}}catch(e){}},DeviceProfile.config.detectInterval);}const render=()=>{if(!currentStream)return;setupCanvas();const W=c.width,H=c.height;if(W<=0||H<=0)return;ctx.clearRect(0,0,W,H);const m=faceDetected?'rgba(16,185,129,0.9)':'rgba(239,68,68,0.9)',g=faceDetected?'rgba(16,185,129,0.5)':'rgba(239,68,68,0.5)';drawCornerBrackets(ctx,W,H,m,g);drawLaserLine(ctx,W,H,m);if(faceDetected&&lastGoodDetection)drawFaceWireframe(ctx,lastGoodDetection,W,H,m);else drawFaceGuide(ctx,W,H,m,g);document.getElementById('scanTime').innerText=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',second:'2-digit'});};startRenderLoop(render);}
function startWorkOverlay(){const c=document.getElementById('faceOverlay'),ctx=c.getContext('2d');setupCanvas();registerResizeHandler();const render=()=>{if(!currentStream)return;const W=c.width,H=c.height;if(W<=0||H<=0)return;ctx.clearRect(0,0,W,H);const cy='rgba(34,211,238,0.9)',cg='rgba(34,211,238,0.5)';drawCornerBrackets(ctx,W,H,cy,cg);drawLaserLine(ctx,W,H,cy);drawRuleOfThirds(ctx,W,H);drawCrosshair(ctx,W,H,cy);drawWorkLabel(ctx,W,H);document.getElementById('scanTime').innerText=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',second:'2-digit'});};startRenderLoop(render);}
function updateStatusUI(d){const s=document.getElementById('scanStatus'),t=document.getElementById('scanStatusText'),i=document.getElementById('scanInstrText');if(d){s.classList.add('detected');t.innerText='FACE LOCKED';i.innerText='Wajah terdeteksi! Tekan shutter';i.style.color='#22c55e';i.style.borderColor='rgba(34,197,94,0.5)';}else{s.classList.remove('detected');t.innerText='SCANNING';i.innerText='Posisikan wajah di dalam frame';i.style.color='rgba(255,255,255,0.7)';i.style.borderColor='rgba(34,211,238,0.4)';}}

// ============================================================
// GPS & GEOFENCING
// ============================================================
function hitungJarak(a,b,c,d){if(!a||!b||!c||!d)return 999999;const R=6371000,dL=(c-a)*Math.PI/180,dG=(d-b)*Math.PI/180,x=Math.sin(dL/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(dG/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function validasiGeoFencing(){const p=dbF[uIdx];let pts=[];if(p.Koordinat_Tugas)try{pts=JSON.parse(p.Koordinat_Tugas);}catch(e){}else if(p.Lat_Kantor)pts=[{nama:"Lokasi Utama",lat:p.Lat_Kantor,lng:p.Lng_Kantor,radius:p.Radius_Meter}];if(!pts.length)return{valid:true,status:'NO_FENCE',jarak:0,radius:0,nama:'Tanpa Batas'};let best=null;for(const pt of pts){const j=hitungJarak(uPos.lat,uPos.lng,pt.lat,pt.lng);if(j<=(pt.radius+20))return{valid:true,status:'IN_ZONE',jarak:Math.round(j),radius:pt.radius,nama:pt.nama||'Lokasi'};if(!best||j<best.jarak)best={jarak:Math.round(j),radius:pt.radius,nama:pt.nama||'Lokasi'};}return{valid:false,status:'OUT_ZONE',jarak:best.jarak,radius:best.radius,nama:best.nama};}
function tampilkanGeoFence(){if(!map)return;const p=dbF[uIdx];let pts=[];if(p.Koordinat_Tugas)try{pts=JSON.parse(p.Koordinat_Tugas);}catch(e){}else if(p.Lat_Kantor)pts=[{lat:p.Lat_Kantor,lng:p.Lng_Kantor,radius:p.Radius_Meter}];if(window.fenceCircles)window.fenceCircles.forEach(c=>map.removeLayer(c));window.fenceCircles=[];pts.forEach(pt=>{if(pt.lat&&pt.lng&&pt.radius)window.fenceCircles.push(L.circle([pt.lat,pt.lng],{color:'#2dd4bf',fillColor:'#2dd4bf',fillOpacity:.15,radius:pt.radius,weight:2}).addTo(map));});if(window.fenceCircles.length&&!isInitialMapBound){map.fitBounds(new L.featureGroup(window.fenceCircles).getBounds().pad(.2));isInitialMapBound=true;}}

function upLoc(){const g=document.getElementById('gpsTxt');g.innerHTML='<i data-lucide="refresh-cw" size="14" style="vertical-align:middle;margin-right:5px;animation:spin 1s linear infinite"></i> Mengunci Sinyal...';lucide.createIcons();if(!navigator.geolocation)return g.innerText="GPS tidak didukung";navigator.geolocation.getCurrentPosition(p=>{if(p.coords.accuracy>250){sndError.play();showToastOnce('gps_lemah',"Sinyal Terlalu Lemah",`Akurasi ${p.coords.accuracy.toFixed(0)}m (>250m).`,"error");g.innerHTML='<i data-lucide="x-circle" size="14" style="vertical-align:middle;margin-right:5px;color:var(--danger)"></i> Sinyal Lemah';lucide.createIcons();uPos={lat:0,lng:0};updateWorkflow();return;}if(p.coords.accuracy>150)showToastOnce('gps_warn',"Peringatan Sinyal",`Akurasi ${p.coords.accuracy.toFixed(0)}m.`,"warning");uPos={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};g.innerHTML=`<i data-lucide="check-circle" size="14" style="vertical-align:middle;margin-right:5px;color:var(--success)"></i> GPS: ${uPos.lat.toFixed(5)}, ${uPos.lng.toFixed(5)}`;lucide.createIcons();if(map){map.setView([uPos.lat,uPos.lng],16);marker.setLatLng([uPos.lat,uPos.lng]);requestAnimationFrame(()=>requestAnimationFrame(()=>map.invalidateSize()));tampilkanGeoFence();}updateWorkflow();},e=>{if(e.code===1)showPermissionModal('gps');else showToastOnce('gps_err',"Gagal","GPS gagal: "+e.message,"error");},{enableHighAccuracy:true,timeout:15000,maximumAge:0});}

// ============================================================
// IMAGE PROCESSING, WATERMARK & CAMERA
// ============================================================
async function compressImage(b64,opt={}){const{maxWidth=1024,maxHeight=1024,quality=0.5,outputWidth=null,outputHeight=null}=opt;return new Promise((res,rej)=>{const img=new Image();const tid=setTimeout(()=>rej(new Error('Timeout')),10000);img.onload=()=>{clearTimeout(tid);const c=document.createElement('canvas');let w=img.width,h=img.height;if(outputWidth&&outputHeight){c.width=outputWidth;c.height=outputHeight;const tr=outputWidth/outputHeight,sr=w/h;let sx,sy,sw,sh;if(sr>tr){sh=h;sw=h*tr;sx=(w-sw)/2;sy=0;}else{sw=w;sh=w/tr;sx=0;sy=(h-sh)/2;}c.getContext('2d').drawImage(img,sx,sy,sw,sh,0,0,outputWidth,outputHeight);}else{if(w>maxWidth){h=h*(maxWidth/w);w=maxWidth;}if(h>maxHeight){w=w*(maxHeight/h);h=maxHeight;}c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);}res(c.toDataURL('image/jpeg',quality));};img.onerror=()=>{clearTimeout(tid);rej(new Error('Gagal memuat'));};img.src=b64;});}

function addWatermark(c){const ctx=c.getContext('2d'),W=c.width,H=c.height,bs=Math.min(W,H),m=bs*0.04;const nf=Math.round(bs*0.032),jf=Math.round(bs*0.022),tf=Math.round(bs*0.020),ff=Math.round(bs*0.018),is=Math.round(bs*0.025),ls=Math.round(bs*0.09);const lx=m,ly=H-m-ls;if(logoCache.complete&&logoCache.naturalWidth>0){ctx.save();ctx.fillStyle='rgba(0,0,0,0.4)';ctx.strokeStyle='rgba(45,212,191,0.5)';ctx.lineWidth=2;ctx.shadowColor='rgba(0,0,0,0.6)';ctx.shadowBlur=10;ctx.shadowOffsetY=3;ctx.beginPath();ctx.roundRect(lx,ly,ls,ls,ls*0.18);ctx.fill();ctx.shadowBlur=0;ctx.stroke();ctx.restore();const ip=ls*0.12;ctx.drawImage(logoCache,lx+ip,ly+ip,ls-ip*2,ls-ip*2);}const tx=lx+ls+bs*0.02,tw=W-tx-m,p=dbF[uIdx],nm=(p.Nama||p.nama||"STAFF").toUpperCase(),jb=(p.Jabatan||"PPA").toUpperCase();const sc={shadowColor:'rgba(0,0,0,0.85)',shadowBlur:8,shadowOffsetX:2,shadowOffsetY:2};ctx.save();ctx.textBaseline='middle';ctx.shadowColor=sc.shadowColor;ctx.shadowBlur=sc.shadowBlur;ctx.shadowOffsetX=sc.shadowOffsetX;ctx.shadowOffsetY=sc.shadowOffsetY;ctx.fillStyle='#fff';ctx.font=`800 ${nf}px 'Plus Jakarta Sans'`;let dn=nm;if(ctx.measureText(dn+' • '+jb).width>tw){dn=nm.substring(0,Math.floor(nm.length*(tw/(ctx.measureText(nm+' • '+jb).width))*0.9))+'...';}ctx.fillText(dn,tx,ly+ls*0.28);const nw=ctx.measureText(dn).width;ctx.fillStyle='#2dd4bf';ctx.font=`600 ${jf}px 'Plus Jakarta Sans'`;ctx.fillText(' • '+jb,tx+nw+6,ly+ls*0.28);ctx.restore();ctx.save();ctx.textBaseline='middle';ctx.shadowColor=sc.shadowColor;ctx.shadowBlur=sc.shadowBlur;ctx.shadowOffsetX=sc.shadowOffsetX;ctx.shadowOffsetY=sc.shadowOffsetY;const l2y=ly+ls*0.58;const gs=`${uPos.lat.toFixed(4)}, ${uPos.lng.toFixed(4)}`;ctx.fillStyle='#2dd4bf';ctx.font=`500 ${tf}px 'JetBrains Mono'`;ctx.fillText(gs,tx+is+8,l2y);const tmx=tx+is+8+ctx.measureText(gs).width+20;if(tmx+is+80<W-m){ctx.fillStyle='#fff';ctx.fillText(new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}),tmx+is+8,l2y);}ctx.restore();ctx.save();ctx.textBaseline='middle';ctx.shadowColor=sc.shadowColor;ctx.shadowBlur=sc.shadowBlur;ctx.shadowOffsetX=sc.shadowOffsetX;ctx.shadowOffsetY=sc.shadowOffsetY;ctx.fillStyle='rgba(255,255,255,0.85)';ctx.font=`700 ${ff}px 'Plus Jakarta Sans'`;ctx.fillText('UPT PUSDA WS BONDOYUDO BARU',tx,ly+ls*0.88);ctx.restore();}

function checkImageQuality(c){const ctx=c.getContext('2d'),d=ctx.getImageData(0,0,c.width,c.height).data;let sb=0,sbq=0,cnt=0;for(let i=0;i<d.length;i+=40){const b=d[i]*0.299+d[i+1]*0.587+d[i+2]*0.114;sb+=b;sbq+=b*b;cnt++;}const avg=sb/cnt,v=(sbq/cnt)-(avg*avg);if(avg<30)return{valid:false,msg:"Foto terlalu gelap."};if(avg>235)return{valid:false,msg:"Foto terlalu silau."};if(v<10)return{valid:false,msg:"Foto terdeteksi blur."};return{valid:true};}

async function capturePhoto(){const v=document.getElementById('vStream');if(v.readyState!==4||v.videoWidth===0)return showToast("Peringatan","Kamera belum siap...","warning");const c=document.createElement('canvas');const[w,h]=cType==='selfie'?DeviceProfile.config.selfieResolution:DeviceProfile.config.kerjaResolution;c.width=w;c.height=h;const ctx=c.getContext('2d');if(cType==='selfie'){ctx.translate(c.width,0);ctx.scale(-1,1);}const vW=v.videoWidth,vH=v.videoHeight,tr=c.width/c.height,sr=vW/vH;let sx,sy,sw,sh;if(sr>tr){sh=vH;sw=sh*tr;sx=(vW-sw)/2;sy=0;}else{sw=vW;sh=sw/tr;sx=0;sy=(vH-sh)/2;}ctx.drawImage(v,sx,sy,sw,sh,0,0,c.width,c.height);ctx.setTransform(1,0,0,1,0,0);if(cType==='selfie'&&isFaceApiLoaded){setLoading(true,"Memindai Wajah...");try{const d=await faceapi.detectSingleFace(c,new faceapi.TinyFaceDetectorOptions({inputSize:320,scoreThreshold:.3}));if(!d){setLoading(false);sndError.play();return showToast("Gagal Deteksi","Wajah tidak terdeteksi!","error");}const q=checkImageQuality(c);if(!q.valid){setLoading(false);sndError.play();return showToast("Kualitas Buruk",q.msg,"error");}}catch(e){}setLoading(false);}sndShutter.play();addWatermark(c);const d=c.toDataURL('image/jpeg',DeviceProfile.config.jpegQuality);if(cType==='selfie'){document.getElementById('sImg').src=d;document.getElementById('sImg').style.display='block';document.getElementById('sPh').style.display='none';sB64=d;}else{document.getElementById('kImg').src=d;document.getElementById('kImg').style.display='block';document.getElementById('kPh').style.display='none';kB64=d;}saveAutoRecovery();stopCam();}

async function triggerCam(type){await ensureFaceApiLoaded();if(isFaceApiLoaded&&!isLandmarkReady)try{await faceapi.nets.faceLandmark68Net.loadFromUri('https://cdn.jsdelivr.net/npm/@vladmandic/face-api/model/');isLandmarkReady=true;}catch(e){}const notes=document.getElementById('notes').value.trim();if(!selectedStatus)return showToast("Peringatan","Pilih status presensi!","warning");if(notes.length<5)return showToast("Peringatan","Keterangan minimal 5 karakter!","warning");cType=type;stopCurrentStream();if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)return triggerFallbackCamera(type);const peg=dbF[uIdx];document.getElementById('scanPegawai').innerText=(peg.Nama||peg.nama||"STAFF").toUpperCase();document.getElementById('scanLogo').src=GITHUB_LOGO_URL;if(type==='selfie'){document.getElementById('scanHeaderTitle').innerText="SECURE FACE VERIFICATION";document.getElementById('scanHeaderSub').innerText="UPT PUSDA • Face Detection Active";document.getElementById('scanInstrText').innerText=DeviceProfile.config.enableFaceAPI?"Posisikan wajah di dalam frame":"Mode Hemat: Arahkan wajah ke frame";document.getElementById('scanStatus').style.display='flex';if(!DeviceProfile.config.enableFaceAPI){document.getElementById('scanStatusText').innerText='BASIC MODE';document.getElementById('scanInstrText').innerText="Mode Hemat: Arahkan wajah ke frame";}}else{document.getElementById('scanHeaderTitle').innerText="LOCATION DOCUMENTATION";document.getElementById('scanHeaderSub').innerText="UPT PUSDA • Work Site Photo";document.getElementById('scanInstrText').innerText="Arahkan kamera ke lokasi kerja";document.getElementById('scanStatus').style.display='none';}lucide.createIcons();const video=document.getElementById('vStream');if(type==='selfie')video.classList.add('mirror');else video.classList.remove('mirror');const{width:iw,height:ih}=DeviceProfile.config.videoConstraints;const con=type==='selfie'?{facingMode:{exact:"user"},width:{ideal:iw},height:{ih}}:{facingMode:{exact:"environment"},width:{ideal:iw},height:{ih}};try{const stream=await navigator.mediaDevices.getUserMedia({video:con,audio:false});currentStream=stream;video.srcObject=stream;document.getElementById('cameraUI').style.display='flex';video.onloadedmetadata=()=>{setupCanvas();video.play().then(()=>{setupCanvas();if(type==='selfie')startSelfieOverlay();else startWorkOverlay();}).catch(()=>{});};}catch(err){if(err.name==='OverconstrainedError')try{const s2=await navigator.mediaDevices.getUserMedia({video:{facingMode:type==='selfie'?"user":"environment"},audio:false});currentStream=s2;video.srcObject=s2;document.getElementById('cameraUI').style.display='flex';video.onloadedmetadata=()=>{setupCanvas();if(type==='selfie')startSelfieOverlay();else startWorkOverlay();};}catch(e2){}if(err.name==='NotAllowedError'){pendingCamType=type;showPermissionModal('camera');}else triggerFallbackCamera(type);}}
function stopCam(){stopCurrentStream();const s=document.getElementById('scanStatus');if(s)s.classList.remove('detected');const t=document.getElementById('scanStatusText');if(t)t.innerText='SCANNING';document.getElementById('cameraUI').style.display='none';}
function triggerFallbackCamera(type){const inp=document.getElementById('fallbackCameraInput');inp.setAttribute('capture',type==='selfie'?'user':'environment');inp.value='';pendingCamType=type;const h=e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/'))return showToast("Format Salah","File harus gambar","error");const r=new FileReader();r.onload=ev=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');const[w,h]=type==='selfie'?DeviceProfile.config.selfieResolution:DeviceProfile.config.kerjaResolution;c.width=w;c.height=h;const ctx=c.getContext('2d');if(type==='selfie'){ctx.translate(c.width,0);ctx.scale(-1,1);}ctx.drawImage(img,0,0,w,h);ctx.setTransform(1,0,0,1,0,0);addWatermark(c);savePhoto(c,type);};img.src=ev.target.result;};r.readAsDataURL(f);inp.removeEventListener('change',h);};inp.addEventListener('change',h);inp.click();}
function savePhoto(c,type){const d=c.toDataURL('image/jpeg',DeviceProfile.config.jpegQuality);sndShutter.play();if(type==='selfie'){document.getElementById('sImg').src=d;document.getElementById('sImg').style.display='block';document.getElementById('sPh').style.display='none';sB64=d;}else{document.getElementById('kImg').src=d;document.getElementById('kImg').style.display='block';document.getElementById('kPh').style.display='none';kB64=d;}showToast("Berhasil","Foto berhasil diambil","success");saveAutoRecovery();}

// ============================================================
// UI HELPERS, WORKFLOWS, RECOVERY
// ============================================================
function updateNotesCounter(){const n=document.getElementById('notes'),c=document.getElementById('notesCounter'),cl=document.getElementById('notesClear'),l=n.value.length;c.textContent=`${l}/500`;c.classList.remove('warning','valid');if(l===0)cl.classList.remove('show');else if(l<5){c.classList.add('warning');cl.classList.add('show');}else{c.classList.add('valid');cl.classList.add('show');}n.style.height='auto';n.style.height=Math.min(n.scrollHeight,200)+'px';}
function clearNotes(){document.getElementById('notes').value='';updateNotesCounter();saveAutoRecovery();}
function onNotesInput(){updateNotesCounter();updateWorkflow();saveAutoRecovery();}
function updateWorkflow(){const g=uPos.lat!==0,s=selectedStatus!=='',n=document.getElementById('notes').value.trim().length>=5;document.getElementById('statusBox1').classList.toggle('workflow-locked',!g);document.getElementById('specialStatusHeader').classList.toggle('workflow-locked',!g);document.getElementById('specialStatusGrid').classList.toggle('workflow-locked',!g);document.getElementById('notesBox').classList.toggle('workflow-locked',!s);document.getElementById('photoBox').classList.toggle('workflow-locked',!n);}
function clearHeavyData(){sB64=null;kB64=null;suratB64=null;document.getElementById('sImg').src="";document.getElementById('kImg').src="";document.getElementById('sImg').style.display='none';document.getElementById('kImg').style.display='none';document.getElementById('sPh').style.display='block';document.getElementById('kPh').style.display='block';document.getElementById('specialStatusGrid').classList.remove('show');document.getElementById('statusBadge').classList.remove('show');document.getElementById('statusInfo').style.display='none';lucide.createIcons();sessionStorage.removeItem('pusda_recovery');}
function saveAutoRecovery(){const d={timestamp:Date.now(),notes:document.getElementById('notes').value,sB64,kB64,suratB64,status:selectedStatus};try{sessionStorage.setItem('pusda_recovery',JSON.stringify(d));}catch(e){try{sessionStorage.setItem('pusda_recovery',JSON.stringify({...d,sB64:null,kB64:null,suratB64:null}));}catch(e2){}}}
function loadAutoRecovery(){const s=sessionStorage.getItem('pusda_recovery');if(s){const d=JSON.parse(s);if(d.timestamp&&(Date.now()-d.timestamp<86400000)){document.getElementById('notes').value=d.notes||"";if(d.sB64){sB64=d.sB64;document.getElementById('sImg').src=sB64;document.getElementById('sImg').style.display='block';document.getElementById('sPh').style.display='none';}if(d.kB64){kB64=d.kB64;document.getElementById('kImg').src=kB64;document.getElementById('kImg').style.display='block';document.getElementById('kPh').style.display='none';}if(d.suratB64)suratB64=d.suratB64;if(d.status){selectedStatus=d.status;updateStatusInfo(selectedStatus);}updateNotesCounter();updateWorkflow();}else sessionStorage.removeItem('pusda_recovery');}}

function updateStatusInfo(s){const i=document.getElementById('statusInfo'),b=document.getElementById('statusBadge'),bt=document.getElementById('statusBadgeText'),ta=document.getElementById('notes'),cfg=STATUS_CONFIG[s];if(!cfg){i.style.display='none';b.classList.remove('show');return;}b.className='status-badge show';if(s==='IZIN')b.classList.add('badge-izin');else if(s==='SAKIT')b.classList.add('badge-sakit');else if(s==='DINAS')b.classList.add('badge-dinas');else if(s==='QUICK RESPONSE')b.classList.add('badge-qr');bt.textContent=s;i.style.display='block';i.style.color=cfg.color;i.style.borderLeftColor=cfg.borderColor;let ah='';if(cfg.actions.length>0){ah='<div class="info-actions">';cfg.actions.forEach(a=>ah+=`<button class="info-action-btn" onclick="${a.action}()"><i data-lucide="${a.icon}" size="12"></i>${a.label}</button>`);ah+='</div>';}i.innerHTML=`<div class="info-title"><i data-lucide="${cfg.icon}" size="18"></i><span>${cfg.title}</span></div><div class="info-body">${cfg.message}</div>${ah}`;ta.placeholder=cfg.placeholder;lucide.createIcons();}
function updateAttendanceStatusIndicator(){const now=new Date(),tv=(now.getHours()*100)+now.getMinutes();let bc=document.getElementById('attendanceStatusIndicator');if(!bc){const sb=document.getElementById('statusBox1');if(sb){bc=document.createElement('div');bc.id='attendanceStatusIndicator';bc.style.width='100%';sb.parentNode.insertBefore(bc,sb.nextSibling);}else return;}if(!selectedStatus||selectedStatus===''){bc.innerHTML='';return;}if(selectedStatus==='PULANG'){bc.innerHTML=`<div class="attendance-status-badge status-ontime"><div class="badge-icon"><i data-lucide="moon" size="18"></i></div><div class="badge-text"><h4>Absen Pulang</h4><p>Terima kasih atas kerja keras Anda hari ini.</p></div></div>`;lucide.createIcons();return;}if(selectedStatus!=='HADIR'){bc.innerHTML='';return;}const pt=t=>{const p=String(t).split(':');return(parseInt(p[0])||0)*100+(parseInt(p[1])||0);};const jh=pt(appConfig.jHadir),jt=pt(appConfig.jTelat);let sc='',ic='',ti='',de='',bc2='#10b981';if(tv<=jh){sc='status-ontime';ic='check-circle';ti='Tepat Waktu';de='Anda mendapat poin penuh (50).';}else if(tv<=jt){sc='status-late-light';ic='clock';ti='Terlambat Ringan';de='Poin dikurangi menjadi 40.';bc2='#facc15';}else{sc='status-late-heavy';ic='alert-octagon';ti='Terlambat Berat';de='Poin dikurangi menjadi 25.';bc2='#ef4444';}bc.innerHTML=`<div class="attendance-status-badge ${sc}"><div class="badge-icon"><i data-lucide="${ic}" size="18"></i></div><div class="badge-text"><h4>${ti}</h4><p>${de}</p></div></div>`;const bh=document.getElementById('btnHadirMain');if(bh&&!bh.classList.contains('btn-done')&&!bh.classList.contains('active')){bh.style.backgroundColor=bc2;bh.style.color='#fff';bh.style.borderColor=bc2;}lucide.createIcons();}

// ============================================================
// DATA FETCHING & SYNC
// ============================================================
function loadFromCache(){const c=localStorage.getItem('pusda_pegawai_v1');if(c){try{dbE=JSON.parse(c);dbF=[...dbE];renderChips();upUI();return true;}catch(e){localStorage.removeItem('pusda_pegawai_v1');return false;}}return false;}
async function loadData(){const st=document.getElementById('initStatusText');if(loadFromCache()){const o=document.getElementById('initialLoadingOverlay');if(o){o.style.opacity='0';o.style.pointerEvents='none';setTimeout(()=>o.style.display='none',400);}silentBackgroundUpdate();return;}if(st)st.innerText="Menghubungkan ke Server...";try{const[r1,r2]=await Promise.all([fetchWithRetry(API+"?action=getDashboardData",{redirect:'follow',cache:'no-cache'},2,2000),fetchWithRetry(API+"?action=getTodayPresensi",{redirect:'follow',cache:'no-cache'},2,2000)]);const[d1,d2]=await Promise.all([r1.json(),r2.json()]);dbE=d1.pegawai||[];dbF=[...dbE];dbP=d2.data||[];try{localStorage.setItem('pusda_pegawai_v1',JSON.stringify(dbE));}catch(e){}document.getElementById('sidebarLogo').src=d1.config?.Logo||GITHUB_LOGO_URL;const cfg=d1.config||{};appConfig.jHadir=cfg.Jam_Hadir||"08:10";appConfig.jTelat=cfg.Jam_Terlambat_Ringan||"08:11";appConfig.jPulang=cfg.Jam_Pulang||"10:00";STATUS_CONFIG.HADIR.message=`<b>Aturan Waktu:</b><br>• ≤ ${appConfig.jHadir} = Poin 50<br>• ${appConfig.jTelat} = Poin 40<br>• > ${appConfig.jTelat} = Poin 25`;if(cfg.Teks_Sambutan){const el=document.getElementById('dynamicWelcome');if(el)el.innerText=cfg.Teks_Sambutan;}if(cfg.URL_Background){const bg=document.querySelector('.fixed-bg');if(bg)bg.style.setProperty('--dynamic-bg-url',`url('${cfg.URL_Background}')`);}renderChips();applyFilters();}catch(e){console.error("Load API Error:",e);if(st)st.innerText="Koneksi Gagal";showToastOnce('load_fail',"Koneksi Gagal","Tidak dapat terhubung ke server.","error");}finally{const o=document.getElementById('initialLoadingOverlay');if(o){o.style.opacity='0';o.style.pointerEvents='none';setTimeout(()=>o.style.display='none',400);}}}
async function silentBackgroundUpdate(){try{const[r1,r2]=await Promise.all([fetchWithTimeout(API+"?action=getDashboardData",{redirect:'follow',cache:'no-cache'},15000),fetchWithTimeout(API+"?action=getTodayPresensi",{redirect:'follow',cache:'no-cache'},15000)]);const[d1,d2]=await Promise.all([r1.json(),r2.json()]);dbE=d1.pegawai||[];dbF=[...dbE];dbP=d2.data||[];try{localStorage.setItem('pusda_pegawai_v1',JSON.stringify(dbE));}catch(e){}const cfg=d1.config||{};appConfig.jHadir=cfg.Jam_Hadir||"08:10";appConfig.jTelat=cfg.Jam_Terlambat_Ringan||"08:11";appConfig.jPulang=cfg.Jam_Pulang||"10:00";STATUS_CONFIG.HADIR.message=`<b>Aturan Waktu:</b><br>• ≤ ${appConfig.jHadir} = Poin 50<br>• ${appConfig.jTelat} = Poin 40<br>• > ${appConfig.jTelat} = Poin 25`;renderChips();applyFilters();}catch(e){console.warn("BG Update fail:",e.message);}}

// ============================================================
// FILTER, NAVIGASI, MAP
// ============================================================
function renderChips(){const w=["ALL",...new Set(dbE.map(p=>(p.Wilayah||p.wilayah||"").trim()).filter(x=>x))];document.getElementById('wilChips').innerHTML=w.map(x=>`<div class="chip-pill ${x==='ALL'?'active':''}" data-wil="${x}" onclick="setWil('${x}',this)">${x}</div>`).join('');}
function setWil(w,el){document.querySelectorAll('.chip-pill').forEach(c=>c.classList.remove('active'));el.classList.add('active');applyFilters();}
function applyFilters(){const s=document.getElementById('searchInput').value.toLowerCase().trim();const ac=document.querySelector('.chip-pill.active');const w=(ac?.getAttribute('data-wil')||'ALL').toLowerCase();const cpid=dbF.length>0?(dbF[uIdx]?.ID||dbF[uIdx]?.id):null;dbF=dbE.filter(p=>{const pw=(p.Wilayah||p.wilayah||"").trim().toLowerCase(),pn=(p.Nama||p.nama||"").toLowerCase();return(w==='all'||pw===w)&&(!s||pn.includes(s));});if(cpid){const ni=dbF.findIndex(p=>(p.ID||p.id)===cpid);uIdx=ni!==-1?ni:0;}else uIdx=0;upUI(w==='all'?'ALL':w);}
function upUI(w="ALL"){const p=dbF[uIdx];if(!p){document.getElementById('pName').innerText="TIDAK DITEMUKAN";document.getElementById('pImg').src=placeholderImg;document.getElementById('pWil').innerText="WILAYAH: "+(w==='all'?'ALL':w);return;}const url=(p.Link_Foto_Profile||p.link_foto_profile||"").split('=')[0]+'=s500';document.getElementById('pWrap').classList.add('loading');const img=document.getElementById('pImg');img.src=(p.Link_Foto_Profile||p.link_foto_profile)?url:placeholderImg;img.onload=()=>document.getElementById('pWrap').classList.remove('loading');document.getElementById('pName').innerText=p.Nama||p.nama;document.getElementById('pJob').innerText=p.Jabatan||p.jabatan||"STAFF";document.getElementById('pWil').innerHTML=`<i data-lucide="map-pin" size="14" style="vertical-align:middle"></i> WILAYAH: ${(p.Wilayah||p.wilayah||"UPT").trim()}`;lucide.createIcons();}
function navU(d){if(!dbF.length)return;uIdx=(uIdx+d+dbF.length)%dbF.length;upUI();}
function initMap(){if(map)return;map=L.map('map',{zoomControl:false,attributionControl:false}).setView([-8.13,113.22],15);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19}).addTo(map);L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_only_labels/{z}/{x}/{y}{r}.png',{maxZoom:19}).addTo(map);marker=L.marker([-8.13,113.22]).addTo(map);requestAnimationFrame(()=>requestAnimationFrame(()=>map.invalidateSize()));}

// ============================================================
// STATUS VALIDATION & FORM LOGIC
// ============================================================
function checkAtt(id,st){return dbP.some(l=>{const lid=String(l['ID Pegawai']||l.id_pegawai||l.ID||'');const ls=String(l.Status||l.status||'').toLowerCase().trim();if(lid!==String(id))return false;if(st==='HADIR')return ls==='hadir'||ls==='terlambat ringan'||ls==='terlambat berat'||ls==='qr hadir'||ls.includes('hadir')||ls.includes('terlambat');if(st==='PULANG')return ls==='pulang'||ls==='qr pulang'||ls.includes('pulang');if(st==='SPECIAL')return ls==='izin'||ls==='sakit'||ls==='dinas';return false;});}

async function openForm(){if(!dbF.length||isFormLoading)return;isFormLoading=true;const ti=uIdx,p=dbF[ti],pid=p.ID||p.id;document.getElementById('stepSelector').style.display='none';document.getElementById('stepForm').style.display='flex';document.getElementById('statusInfo').style.display='none';document.getElementById('statusBadge').classList.remove('show');selectedStatus='';document.querySelectorAll('.btn-presence-mega,.btn-special-status').forEach(i=>i.classList.remove('active'));document.getElementById('specialStatusGrid').classList.remove('show');lucide.createIcons();document.getElementById('formHeroImg').src=(p.Link_Foto_Profile||p.link_foto_profile||"").split('=')[0]+'=s500'||placeholderImg;document.getElementById('formName').innerText=p.Nama||p.nama;document.getElementById('formJobWil').innerHTML=`<i data-lucide="briefcase" size="14" style="vertical-align:middle"></i> ${p.Jabatan||"PPA"} | <i data-lucide="map-pin" size="14" style="vertical-align:middle"></i> ${p.Wilayah||"UPT"}`;lucide.createIcons();const bh=document.getElementById('btnHadirMain'),bp=document.getElementById('btnPulangMain');bh.style.pointerEvents='none';bh.style.opacity='0.5';bp.style.pointerEvents='none';bp.style.opacity='0.5';try{const r=await fetchWithTimeout(API+"?action=getTodayPresensi",{redirect:'follow',cache:'no-cache'},12000);dbP=(await r.json()).data||[];}catch(e){}if(document.getElementById('stepForm').style.display!=='flex'||(dbF[uIdx]?.ID||dbF[uIdx]?.id)!==pid){isFormLoading=false;return;}bh.classList.remove('btn-done','active');bh.innerHTML='<i data-lucide="sun" size="28"></i><span>HADIR</span>';bh.style.pointerEvents='';bh.style.opacity='';bp.classList.remove('btn-done','active');bp.innerHTML='<i data-lucide="moon" size="28"></i><span>PULANG</span>';bp.style.pointerEvents='';bp.style.opacity='';if(checkAtt(pid,'HADIR')){bh.classList.add('btn-done');bh.innerHTML='<i data-lucide="check-circle" size="28"></i><span>SUDAH HADIR</span>';}if(checkAtt(pid,'PULANG')){bp.classList.add('btn-done');bp.innerHTML='<i data-lucide="check-circle" size="28"></i><span>SUDAH PULANG</span>';}lucide.createIcons();updateAttendanceStatusIndicator();updateNotesCounter();updateWorkflow();setTimeout(()=>{initMap();upLoc();loadAutoRecovery();},300);isFormLoading=false;}
function closeForm(){document.getElementById('stepSelector').style.display='flex';document.getElementById('stepForm').style.display='none';isFormLoading=false;}

function setS(el,st){if(uPos.lat===0)return showToast("Peringatan","Tunggu GPS mengunci lokasi!","warning");const g=validasiGeoFencing(),out=g.status==='OUT_ZONE',exc=['IZIN','SAKIT','DINAS','QUICK RESPONSE'].includes(st);if(out&&!exc){sndError.play();showToast("Ditolak",`Anda di luar area (${g.jarak}m).`,"error");return;}haptic();const p=dbF[uIdx],pid=p.ID||p.id,now=new Date(),tv=(now.getHours()*100)+now.getMinutes();const hasSp=checkAtt(pid,'SPECIAL');if(hasSp&&!['IZIN','SAKIT','DINAS'].includes(st))return sndError.play(),showToast("Ditolak","Sudah ada status IZIN/SAKIT/DINAS.","error");if(['IZIN','SAKIT','DINAS'].includes(st)){if(hasSp)return sndError.play(),showToast("Sudah Diajukan","Sudah ada status khusus.","error");if(checkAtt(pid,'HADIR'))return sndError.play(),showToast("Ditolak","Sudah HADIR, tidak bisa ajukan status khusus.","error");}if(st==='HADIR'&&checkAtt(pid,'HADIR'))return sndError.play(),showToast("Sudah Absen","Sudah melakukan presensi HADIR.","error");if(st==='PULANG'){if(checkAtt(pid,'PULANG'))return sndError.play(),showToast("Sudah Absen","Sudah melakukan presensi PULANG.","error");if(!checkAtt(pid,'HADIR'))return sndError.play(),showToast("Urutan Salah","Harap absen HADIR terlebih dahulu.","error");}if(st==='QUICK RESPONSE'){if(tv<1000){if(checkAtt(pid,'HADIR'))return sndError.play(),showToast("Sudah Absen","Sudah HADIR/QR HADIR.","error");}else{if(checkAtt(pid,'PULANG'))return sndError.play(),showToast("Sudah Absen","Sudah PULANG/QR PULANG.","error");if(!checkAtt(pid,'HADIR'))return sndError.play(),showToast("Belum Absen","Belum HADIR/QR HADIR.","error");}}document.querySelectorAll('.btn-presence-mega,.btn-special-status').forEach(i=>i.classList.remove('active'));el.classList.add('active');selectedStatus=st;updateStatusInfo(st);updateAttendanceStatusIndicator();updateWorkflow();saveAutoRecovery();}

function updateMainButtons(){const bh=document.getElementById('btnHadirMain'),bp=document.getElementById('btnPulangMain');if(selectedStatus==='HADIR'){bh.classList.add('btn-done');bh.innerHTML='<i data-lucide="check-circle" size="28"></i><span>SUDAH HADIR</span>';}else if(selectedStatus==='PULANG'){bp.classList.add('btn-done');bp.innerHTML='<i data-lucide="check-circle" size="28"></i><span>SUDAH PULANG</span>';}else if(selectedStatus==='QUICK RESPONSE'){const tv=(new Date().getHours()*100)+new Date().getMinutes();if(tv<1000){bh.classList.add('btn-done');bh.innerHTML='<i data-lucide="check-circle" size="28"></i><span>SUDAH QR HADIR</span>';}else{bp.classList.add('btn-done');bp.innerHTML='<i data-lucide="check-circle" size="28"></i><span>SUDAH QR PULANG</span>';}}lucide.createIcons();}

// ============================================================
// SUBMIT PRESENSI (PREMIUM EDITION)
// ============================================================
async function submitWithRetry(attempt=1){const btn=document.getElementById('btnSubmitPresensi'),n=document.getElementById('notes').value.trim();if(!selectedStatus)return showToast("Peringatan","Pilih status!","warning");if(!n||n.length<5)return showToast("Peringatan","Keterangan minimal 5 karakter!","warning");if(!sB64)return showToast("Data Belum Lengkap","Foto selfie wajib!","warning");if(!kB64)return showToast("Data Belum Lengkap","Foto lokasi wajib!","warning");const needSurat=['IZIN','SAKIT','DINAS'].includes(selectedStatus);if(needSurat&&!suratB64){setLoading(true,"Memeriksa kelengkapan...");const uc=await showSuratModal();if(uc==='attach'){setLoading(false);uploadSurat();return;}}btn.disabled=true;const p=dbF[uIdx],t0=performance.now();try{await MissionControl.start();await MissionControl.nextStep();await MissionControl.nextStep();await MissionControl.nextStep();await new Promise(r=>setTimeout(r,Math.random()*1500));const payload={action:'presensi',idPegawai:p.ID,nama:p.Nama,status:selectedStatus,selfie:sB64,workPhoto:kB64,surat:suratB64||'-',keterangan:n,gps:`${uPos.lat},${uPos.lng}`,wilayah:p.Wilayah||"-"};const r=await fetchWithTimeout(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)},30000);const j=await r.json();await MissionControl.nextStep();await new Promise(r=>setTimeout(r,600));if(j.status==='success'||j.result==='success'){const dur=((performance.now()-t0)/1000).toFixed(1);logPerformance('presensi',performance.now()-t0);saveLastPegawai(p);await MissionControl.showSuccess();dbP.push({'ID Pegawai':String(p.ID||p.id),'Status':j.statusFix||selectedStatus,'Timestamp':new Date().toISOString()});updateMainButtons();clearHeavyData();btn.disabled=false;}else if(j.status==='error'){MissionControl.showError(j.message||"Ditolak");sndError.play().catch(()=>{});await new Promise(r=>setTimeout(r,2000));MissionControl.hide();showToast("Ditolak",j.message||"Gagal menyimpan.","error");btn.disabled=false;}else throw new Error(j.message||"Format respons tidak dikenal");}catch(e){console.error("Error submit:",e);if(attempt<4){MissionControl.showError("Koneksi terputus, menghubungkan kembali...");await new Promise(r=>setTimeout(r,2000));MissionControl.hide();setTimeout(()=>submitWithRetry(attempt+1),500);}else{MissionControl.showError("Gagal total. Data aman di HP Anda.");sndError.play().catch(()=>{});await new Promise(r=>setTimeout(r,2000));MissionControl.hide();showToast("Gagal Mengirim","Server sibuk. Silakan coba lagi nanti.","error");btn.disabled=false;}}}

// MODALS & EXTRAS
function showSuratModal(){return new Promise(res=>{const m=document.getElementById('suratModal');if(!m)return res('skip');document.getElementById('modalStatusText').innerText=selectedStatus;lucide.createIcons();m.style.display='flex';requestAnimationFrame(()=>m.classList.add('show'));const cl=()=>{m.classList.remove('show');setTimeout(()=>m.style.display='none',300);document.getElementById('btnModalAttach').onclick=null;document.getElementById('btnModalSkip').onclick=null;};document.getElementById('btnModalAttach').onclick=()=>{cl();res('attach');};document.getElementById('btnModalSkip').onclick=()=>{cl();res('skip');};});}
async function uploadSurat(){const inp=document.getElementById('suratInput');inp.value='';const h=async e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/'))return showToast("Format Salah","File harus gambar","error");if(f.size>5*1024*1024)return showToast("Ukuran Melebihi Batas","Maksimal 5MB","error");setLoading(true,"Mengompresi surat...");const r=new FileReader();r.onload=async ev=>{try{const c=await compressImage(ev.target.result,{maxWidth:800,maxHeight:800,quality:0.5});suratB64=c;setLoading(false);showToast("Berhasil",`Surat terkompresi (${Math.round((c.length*0.75)/1024)}KB)`,"success");saveAutoRecovery();}catch(err){setLoading(false);showToast("Gagal","Gagal mengompresi","error");}};r.readAsDataURL(f);inp.removeEventListener('change',h);};inp.addEventListener('change',h);inp.click();}
function triggerGallery(){if(!selectedStatus)return showToast("Peringatan","Pilih status dulu!","warning");if(document.getElementById('notes').value.trim().length<5)return showToast("Peringatan","Keterangan minimal 5 karakter!","warning");const inp=document.getElementById('galleryInput');inp.value='';const h=e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/'))return showToast("Format Salah","File harus gambar","error");const r=new FileReader();r.onload=ev=>{const img=new Image();img.onload=async()=>{setLoading(true,"Mengompresi foto...");try{const c=await compressImage(ev.target.result,{outputWidth:600,outputHeight:800,quality:0.4});addWatermark(c);const d=c.toDataURL('image/jpeg',0.4);document.getElementById('kImg').src=d;document.getElementById('kImg').style.display='block';document.getElementById('kPh').style.display='none';kB64=d;setLoading(false);sndShutter.play();showToast("Berhasil","Foto lokasi tersimpan","success");saveAutoRecovery();}catch(err){setLoading(false);showToast("Gagal","Gagal mengompresi","error");}};img.src=ev.target.result;};r.readAsDataURL(f);inp.removeEventListener('change',h);};inp.addEventListener('change',h);inp.click();}
function showPermissionModal(type){const m=document.getElementById('permissionModal'),t=document.getElementById('permTitle'),d=document.getElementById('permDesc'),s=document.getElementById('permSteps'),b=document.getElementById('permRetryBtn');if(type==='camera'){t.innerText='Akses Kamera Dibutuhkan';d.innerText='Izinkan akses kamera untuk foto presensi.';s.innerHTML='<div class="permission-step"><div class="permission-step-num">1</div><div>Klik <b>Coba Lagi</b></div></div><div class="permission-step"><div class="permission-step-num">2</div><div>Pilih <b>Izinkan</b></div></div>';b.onclick=()=>{closePermissionModal();triggerCam(pendingCamType);};}else{t.innerText='Akses Lokasi Dibutuhkan';d.innerText='GPS diperlukan untuk verifikasi lokasi.';s.innerHTML='<div class="permission-step"><div class="permission-step-num">1</div><div>Aktifkan <b>GPS HP</b></div></div><div class="permission-step"><div class="permission-step-num">2</div><div>Klik <b>Coba Lagi</b></div></div>';b.onclick=()=>{closePermissionModal();upLoc();};}m.classList.add('show');lucide.createIcons();}
function closePermissionModal(){document.getElementById('permissionModal').classList.remove('show');}
function toggleSpecialStatus(){const g=document.getElementById('specialStatusGrid'),h=document.getElementById('specialStatusHeader'),i=document.getElementById('collapseIcon');g.classList.toggle('show');h.classList.toggle('open');i.setAttribute('data-lucide',g.classList.contains('show')?'chevron-up':'chevron-down');lucide.createIcons();}
function startVoice(id,btn){const S=window.SpeechRecognition||window.webkitSpeechRecognition;if(!S)return;const r=new S();r.lang='id-ID';r.onstart=()=>{btn.classList.add('active');haptic();};r.onresult=e=>{const t=e.results[0][0].transcript;if(id==='searchInput'){document.getElementById('searchInput').value=t;applyFilters();}else{const n=document.getElementById('notes');n.value+=(n.value?' ':'')+t;onNotesInput();}};r.onend=()=>btn.classList.remove('active');r.onerror=()=>btn.classList.remove('active');r.start();}

// ============================================================
// INITIALIZATION
// ============================================================
window.onload=()=>{lucide.createIcons();loadData();updateAttendanceStatusIndicator();setInterval(updateAttendanceStatusIndicator,60000);setInterval(()=>{const t=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'});const c=document.getElementById('liveClock');if(c)c.innerText=t;const vc=document.getElementById('verticalClock');if(vc)vc.innerText=t;},1000);window.addEventListener('offline',()=>showToast("Offline","Koneksi terputus.","warning"));window.addEventListener('online',()=>{showToast("Online","Koneksi pulih.","success");silentBackgroundUpdate();});};
